name: Main workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup github config
        run: |
          git config --global user.email "zimanovalikhan07@gmail.com"
          git config --global user.name "Alikhan Zimanov"

      - name: Docker part
        run: |
          rm CV/main.pdf
          docker build -t image .
          docker run -v "$PWD"/CV:/temp image
        
      - name: Committing changes
        run:
          git add CV/main.pdf
          git commit -m 'LOL'
#          touch super_kek.txt
#          echo 'hello world'>super_kek.txt
#          git add super_kek.txt
#          git commit -m 'kek'
#          git push