name: Main workflow

on: [ push ]

jobs:
  compiling_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup github config
        run: |
          git config --global user.email "zimanovalikhan07@gmail.com"
          git config --global user.name "Alikhan Zimanov"

      - name: Docker part
        run: |
          rm CV/main.log
#          rm CV/main.pdf
#          docker build -t image .
#          docker run -v "$PWD"/CV:/temp image
        
      - name: Committing changes
        run: |
          git add CV/main.log
          git add CV/main.pdf
          git commit -m 'Hmm'

  pushing_to_pages:
    needs: compiling_pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup github config
        run: |
          git config --global user.email "zimanovalikhan07@gmail.com"
          git config --global user.name "Alikhan Zimanov"
        
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: to_pages
          folder: CV/main.pdf
