name: Main workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker part
        run: |
          touch super_kek.txt
          echo 'hello world'>super_kek.txt
          git commit -a -m 'lol'
          git push
#        run: |
#          docker build -t image .
#          docker run -v "$PWD"/CV:/code image